<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Erp_Pickup_Area extends MY_RetailErp_Model {
	protected $table = 'pickup_area';

	/**
	 * @var int
	 */
	public $warehouse_id;

	/**
	 * @var int
	 */
	public $area_id;

	/**
	 * @return int
	 */
	public function getWarehouseId(): int {
		return $this->warehouse_id;
	}

	/**
	 * @param int $warehouse_id
	 */
	public function setWarehouseId( int $warehouse_id ): void {
		$this->warehouse_id = $warehouse_id;
	}

	/**
	 * @return int
	 */
	public function getAreaId(): int {
		return $this->area_id;
	}

	/**
	 * @param int $area_id
	 */
	public function setAreaId( int $area_id ): void {
		$this->area_id = $area_id;
	}

	public function save() {

		$save = parent::save();
		return $save;
	}

	public function delete() {
		return parent::delete(); // TODO: Change the autogenerated stub
	}

}
// End of file Erp_package_items.php.
